### PR TITLE
Update GPAW recipes

### PR DESCRIPTION
**Pull request by trossi**
This PR will update GPAW recipes
* Update siteconfig files (include e.g. missing `compiler_args = []  # remove all default args`)
* Use stable tarball from pypi (otherwise build fails for incorrect checksum)
* Add recipes for GPAW 24.6.0 (latest release)
* Remove recipes for older releases
* Update recipes to use CPE 24.03

~~All GPU tests pass for GPAW 24.6.0 with single GPU but not with multiple GPUs (on-going development). GPAW 24.1.0 had many more tests failing so recipes are removed.~~ All GPU tests do not pass (see discussion below).

### CODE REVIEW

**Review by mszpindler — COMMENTED** [review]
Minor changes to align with updated rocm/6 software stack. To be merged after #192.

**Comment by mszpindler** [comment]
@trossi could you please share which GPU test you were using to evaluate these recipes?

**Comment by trossi** [comment]
@mszpindler Thanks for updating the recipes! I was running the pytests like this (added to [GPAW wiki](https://wiki.fysik.dtu.dk/gpaw/platforms/Cray/lumi.html) too):

    n=1; srun -p small-g --nodes=1 --ntasks-per-node=$n --gpus-per-node=$n -t 00:10:00 gpaw python -m pytest FIX_PATH/lib/python3.10/site-packages/gpaw/test/ -v -m gpu --basetemp=$PWD/tmp/pytest-gpu-$n --disable-pytest-warnings

Here `-m gpu` selects GPU tests only, `n` is the number of GPUs, and `FIX_PATH` needs to be fixed. It's a bit hacky as it uses the installation path to `gpaw/test/`, but this seemed more robust way of running pytest than some other ways.

Some tests failed with multiple GPUs but all single-GPU tests passed.

**Comment by mszpindler** [comment]
I have failures from `lib/python3.10/site-packages/gpaw/test/gpu/test_pw.py` on a single GPU:
```
=========================== short test summary info ============================
FAILED ../../../../project/project_462000008/maciszpin/LUMI-user/SW/LUMI-23.09/G/GPAW/24.6.0-cpeGNU-23.09-rocm/lib/python3.10/site-packages/gpaw/test/gpu/test_pw.py::test_gpu[fd-True-complex]
FAILED ../../../../project/project_462000008/maciszpin/LUMI-user/SW/LUMI-23.09/G/GPAW/24.6.0-cpeGNU-23.09-rocm/lib/python3.10/site-packages/gpaw/test/gpu/test_pw.py::test_gpu_k[LDA-fd-domain-True]
FAILED ../../../../project/project_462000008/maciszpin/LUMI-user/SW/LUMI-23.09/G/GPAW/24.6.0-cpeGNU-23.09-rocm/lib/python3.10/site-packages/gpaw/test/gpu/test_pw.py::test_gpu_k[PBE-fd-domain-True]
======= 3 failed, 13 passed, 16 skipped, 3 warnings in 108.73s (0:01:48) =======
```
All 3 are of type `KohnShamConvergenceError`.

**Comment by trossi** [comment]
Interesting. I got earlier this same issue with multiple GPUs only (or, to be more precise, with multiple MPI tasks whether they were using the same or different GPUs), but with single GPU this test was passing. For curiosity, could you try running this test alone by giving path to this test only: `srun ... FIX_PATH/lib/python3.10/site-packages/gpaw/test/gpu/test_pw.py ...`? Earlier some tests passed that way indicating an issue in GPAW code.

**Comment by mszpindler** [comment]
> Interesting. I got earlier this same issue with multiple GPUs only (or, to be more precise, with multiple MPI tasks whether they were using the same or different GPUs), but with single GPU this test was passing. For curiosity, could you try running this test alone by giving path to this test only: `srun ... FIX_PATH/lib/python3.10/site-packages/gpaw/test/gpu/test_pw.py ...`? Earlier some tests passed that way indicating an issue in GPAW code.

It is exactly what I did.

**Comment by trossi** [comment]
@mszpindler Thanks! We can have a look on this issue after the maintenance break.

**Comment by trossi** [comment]
@mszpindler I can reproduce the same GPU tests errors with CPE 24.03 too (and these errors are different than those with rocm 5 before the maintenance). I'd suspect there is some issue in GPAW code itself and we'll look into that.

I updated the recipes to CPE 24.03 and added a warning about GPU versions. This PR would be ready for review and merging from my perspective, so that we get up-to-date CPU-version recipes to easybuild (requested by users). We could also remove the GPU recipes if they are too unstable in your opinion (in practice, developer installation would be recommended for GPU version).

**Review by mszpindler — APPROVED** [review]

**Pull request merged**
