### PR TITLE
Easyconfigs for PETSc CPU (cpeGNU) and GPU (cpeCray)

### PR DESCRIPTION
**Pull request by mszpindler**

### CODE REVIEW

**Comment by mszpindler** [comment]
Still needs to handle `make check` correctly while this should show up if the library is linkable.

**Comment by mszpindler** [comment]
There is now `make check_build` in the runtest stage added. Although it is marked as ignorable with `-` make prefix in the makefile and I am not sure if it is possible to force it not to be ignored.

**Comment by mszpindler** [comment]
All in all it is for checking if resulting library is linking correctly. `openmp` toolchain opt is required for GPU build.

**Comment by mszpindler** [comment]
PETSc CPU and GPU are now good.

**Comment by klust** [comment]
Not as complete as it could be but good enough for a first version so pulled in as is.

**Pull request merged**
