### PR TITLE
Add recipe for hpc-container-wrapper developed by Henrik Nortamo.

### PR DESCRIPTION
**Pull request by mszpindler**
Waiting for minor fix in Henrik's code.

### CODE REVIEW

**Comment by Nortamo** [comment]
The version should be bumped to `v0.2.2`, no changes in the interface but some bugfixes done.

**Comment by klust** [comment]
I've modified the EasyBuild install a bit (renamed to tykky and updated the version as requested) to align with the documentation and with the name used on puhti and mahti, but I cannot get the example to work. It is not clear if this is a problem with the wrapper or with the documentation.

**Comment by olouant** [comment]
Not a big fan of the renaming. "Container-Wrapper" describe what the tool do (the same applies to the documentation) which help in the self-advertisement of the tool via `module av`.

**Comment by Nortamo** [comment]
> I've modified the EasyBuild install a bit (renamed to tykky and updated the version as requested) to align with the documentation and with the name used on puhti and mahti, but I cannot get the example to work. It is not clear if this is a problem with the wrapper or with the documentation.

My guess is the default config. That currently use `/tmp/$USER` as a working directory but will not create the directory if it does not exist, instead throwing an error.  In this case the error should look like `Build directory /tmp/$USER='/tmp/nortamoh' does not exist`

I'll patch it to create that directory if it does not exist or would you prefer to use just /tmp instead?. As far as I can tell there is yet no "$TMPDIR" variable set on Lumi.

If it's some other issue, do you have some more information on that, I ran the regression test for the newest version and
they look fine.

**Comment by klust** [comment]
It looks like the problem may have been a non-issue.

I bumped into the /tmp/$USER problem but that was easily dealt with by following the instructions in the error message and defining an environment variable pointing to an available work space.

I was following the end-to-end example from https://github.com/Lumi-supercomputer/lumi-userguide/blob/Nortamo-add-wrapper-docs/docs/computing/containers/tykky.md. The command
``` 
conda-containerize new --prefix MyEnv env.yml 
```
failed after a few minutes but when I tried again this afternoon it turned out that either some error message was not printed (as it may have crashed at a slightly different point this morning) or it was no scrolled onto the screen or so. The underlying problem was likely running out of file quota in the directory that I was using for the cache this morning also though I then only saw some error messages from something that went wrong just before the out-of-quota message was displayed.

I know tried again pointing to the scratch for temp, and that produces a lot of error messages " Unrecognised xattr prefix lustre.lov"  so I guess we should really use some local directory or a RAM disk for building the wrapper? ($XDG_RUNTIME_DIR might be an option on the login nodes, but not on the compute nodes as the daemon needed for that is not running on those nodes?) Despite the error message the produced image does work so far though.

**Comment by Nortamo** [comment]
Fixed the build dir creation and retagged so no changes required on that part for the recipe. 
Changed the name in the documentation to Lumi container wrapper

**Pull request merged**
