### PR TITLE
Add easyconfig for module to enable MPI support of singularity

### PR DESCRIPTION
**Pull request by rsarm**
It has some versions hardcoded inside, maybe we can find env variables to replace them.

The glibc part it's not useful for all containers. It's only useful in those that have a glibc version older than the one installed on the host. That can cause conflicts in some case within the containers but I think including the glibc binds cover most of the cases.

### CODE REVIEW

**Comment by klust** [comment]
- Is there a reason why you use mpich 8.1.5 but cpeGNU 21.08? The version of MPICH that came with the 21.08 release was cray-mpich 8.1.8.
- Should we name this module "singularity" or something like "singularity-biondings"? Singularity is provided by the OS, so at the next OS update its version may change while everything that the module does will likely work as long as the 21.08 environment is on the system. So wouldn't it make more sense to have the module named something link singularity-bindings/21.08-cpeGNU-21.08? (I know, the 21.08 is double in the name but that is also a consequence of the fact that we don't use a hierarchical naming scheme).
- Just a question - I am not a singularity expert. I guess the reason for using cray-mpich-abi and putting /opt/cray/pe/mpich/8.1.5/ofi/gnu/9.1/lib-abi-mpich in SINGULARITY_LD_LIBRARY_PATH rather than just /opt/cray/pe/lib64 is because the symbolic links in the latter don't work in a container if the directory pointed to isn't also made available in the container?

Naming is kind of tricky as there are two dependencies that are updated independently from each other. The cray-mpich-abi version depends on the available programming environments while the version of libfabric probably depends on the OS release or some other version in the Cray software stack as it is also not installed under /opt/cray/pe. So this is a module that we will need to put on a list of modules that should definitely be checked after every upgrade in the system.

**Comment by rsarm** [comment]
The path comes from the the `cray-mpich-abi` module for the MPICH ABI compatibility.

I would keep the `<singularity-version>-CrayGNU-xxx.eb` name. If there's an os update that breaks the recipe, I guess we just update it instead of creating a new one.

For the versions, it would be nice if we had environment variables instead. There is `CRAY_MPICH_DIR` for the `cray-mpich-abi` path but I can't find anything for the version of the libfabric module. Also I have the impression that chaining multiple paths on a lua module it's a bit long, and it might make the recipe a hard to read. What do you think?

**Comment by rsarm** [comment]
@klust I didn't understand your comment about the singularity version. Indeed, since we have only on version of singularity, we don't need it on the easyconfig. What do you think of versioning it with the version of the libfabric module? Like this we should be able to control the two possibly problematic paths on the recipe: the mpich path with `CRAY_MPICH_DIR ` and the libfabric path with `%(version)s`.

**Comment by rsarm** [comment]
@klust I didn't understand your comment about the singularity version. Indeed, since we have only on version of singularity, we don't need it on the easyconfig. What do you think of versioning it with the version of the libfabric module? Like this we should be able to control the two possibly problematic paths on the recipe: the mpich path with `CRAY_MPICH_DIR ` and the libfabric path with `%(version)s`.

**Comment by klust** [comment]
I thought a bit about it. I think I would simply use "system" as the version to stress that singularity itself comes with the system. The problem of the Cray MPICH and libfabric versions is difficult to deal with in the EasyConfig. I tend to define those version numbers also in separate variables that I then use to build the arguments for modextravars etc.

It is not really possible to use CRAY_MPICH_DIR in the easyconfig because that would assume that the variable is set already when EasyBuild processes the easyconfig. All one can try is see what happens if you embed a Lua statement instead in the strings passed to modextravars but that is tricky. There has recently been a request to implement the use of environment variables in the argument of modextravars but so far there were not enough use cases to make this a high prioriy.

My suggestion to deal with the version problem for Cray MPICH and libfabric would be to keep things like it is now, see if the module indeed works for several people, and then I can write the needed LUA code instead and put it in a modluafooter line (similar to what CSCS does in their easyconfigs for cpeGNU etc I believe). There I can pick things up from the environment and I am fluent enough in LUA and the restrictions it has in Lmod (because of sandboxing of the execution of the module code) that I can write a piece of code to parse the environment and extract the libfabric directory from LD_LIBRARY_PATH. libfabric is loaded by craype-network-ofi so that should already be present in the environment when the singularity module loads, and I have to double-check but I Lmod seems to have its tricks to ensure that setting an environment variable can also already be detected in the module.

**Comment by klust** [comment]
In the list of libraries for glibc there is /_pizdaint/ld-linux-x86-64.so.2 which I guess is not for us. But do you know if this points to a particular problem with that library that we may also run into on LUMI?

**Comment by rsarm** [comment]
Thanks @klust! I used to put them all on a folder `_pizdaint` instead of replacing them within the container. That one was a left over, it's the same as the last one in the list.

**Pull request merged**
